### ISSUE TITLE
Suggestion to enforce guidelines

### ISSUE THREAD

**Issue by jadb** [aws/aws-week-in-review#1]
Hi,

I just saw your tweet and after checking the README file, noticed there was some _contribution_ guidelines mixed in there.

I'd like to suggest using `CONTRIBUTING.md` to put those guidelines as GitHub will automatically show a link to them to everyone submitting a new PR.

I would also like to take this opportunity to present something I am directly affiliated with and that could help enforcing those guidelines: https://var.ci

The reason I say that is because it would help contributors automatically know of mistakes they've made while saving you time from having to manually do it yourself.

I hereby volunteer to create the initial PR to get things set up if you give me the OK.

Best,

Jad

**Comment by jeffbarr** [comment]
Hi @jadb , great suggestion. I have added a starter version of `CONTRIBUTING.md` and will add to it as soon as the project gets going. Please feel free to take a look and let me know what you think.

Your project looks like it could be a big help to mine; please feel free to set up the PR. I do want to keep things as easy as possible for contributors.

Thanks,

Jeff;
