### ISSUE TITLE
Broken "pull request" link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ehammond** [aws/aws-week-in-review#132]
CONTRIBUTING.md has a "pull request" hyperlink to https://help.github.com/send-pull-requests/ which does not exist.

**Comment by ehammond** [comment]
Thanks @rjhintz 

Not sure why this issue didn't auomatically close. Perhaps you need to include the magic (fixes #132) text in the commit text.

**Comment by rjhintz** [comment]
@ehammond   Thanks. I was wondering.

Edit to add: oops, I just RTFM and, yes, omitted magic words in closing via commit.
