### ISSUE TITLE
Need a cutoff date (& time?) in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rjhintz** [aws/aws-week-in-review#167]
It's unclear when contributors should stop submitting PRs for the current file and start using the next iteration. 

It may make sense to have both this week's and the next week's files up with some guidance added to CONTRIBUTING.md.

**Comment by jeffbarr** [comment]
Good idea, I will add some info ASAP.

**Comment by rjhintz** [comment]
No problem on when you get to it. I'm hoping this PR oriented new method of producing the "This Week" doesn't prove to be a bigger ongoing pain than what you were doing before.

I'm hopeful that we will be able to come up with something that implements automation.

**Comment by martinb3** [comment]
I'm confused -- I even see new submissions being merged (as of a few hours ago) to the October 3rd post. Didn't that go out already? It would be good to understand when a new week's post will be created too.

**Comment by jeffbarr** [comment]
I added a weekly schedule to the README; all of the action happens on Monday mornings on my side. @martinb3 , if I see a post-publication pull request appear I will copy it over to WordPress ; I don't want anyone to end up doing work that is ignored.
