### ISSUE TITLE
Can we use template engine instead of pure HTML?

### ISSUE THREAD

**Issue by miglen** [aws/aws-week-in-review#20]
Hi everyone,
just as a suggestion can we use template engine, or Markdown instead of writing pure HTML?

**Comment by carlnordenfelt** [comment]
+1 for markdown

**Comment by jeffbarr** [comment]
This is a really good suggestion! Unfortunately, Markdown does not work within HTML, so I cannot make the enclosing table look good. I'm definitely open to suggestions and contributions that would enable the use of Markdown.
