### ISSUE TITLE
Refactor Contributing and ReadMe: Move Short Code Info to Contributing

### ISSUE THREAD

**Issue by rjhintz** [aws/aws-week-in-review#257]
All the information needed to contribute might better be in Contributing, rather than in ReadMe.

One change would be to move the short code information to Contributing.

**Comment by hyandell** [comment]
I discussed with @jeffbarr. The Week in Review is no longer being published. You can visit https://aws.amazon.com/new/ to track the latest product, service, and feature announcements from AWS.
