### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by ffcgoering** [aws/aws-week-in-review#273]
I think it would be useful if links in the Week in Review opened in a new tab.  It would make navigating easier than having to use the back-button to return to the page or having to manually choose to open in a new tab.

**Comment by rjhintz** [comment]
I'd recommend against this since it's unexpected behavior. 

It's generally simple enough for someone to use their browser's method, usually one click, for opening a new tab if they really want this behavior.

**Comment by ffcgoering** [comment]
If you advise that links will open in a new tab, I feel that it is common enough of a convention so as to not cause usability issues.  Particularly in cases such as this when linking to outside resources. However I suppose in the end it's a matter of what the majority would find to be most efficient.

Chris

Chris Goering
Focus Forward
Application Development Director

www.focusfwd.comhttp://www.focusfwd.com
302.220.7220

On Tue, Oct 18, 2016 at 5:54 PM -0400, "Rich Hintz" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'd recommend against this since it's unexpected behavior.

It's generally simple enough for someone to use their browser's method, usually one click, for opening a new tab if they really want this behavior.

**Comment by jeffbarr** [comment]
I appreciate the suggestion but I am not a big fan of this behavior. I prefer to control-click to open links in new tabs. Thanks for contributing!
