### ISSUE TITLE
Alternative list of sources

### ISSUE THREAD

**Issue by inakiabt** [aws/aws-week-in-review#4]
I've found this [repo](https://github.com/kilimchoi/engineering-blogs) while ago that compile a (huge) well categorized list of engineering blogs and generates an OPML.
I'm not sure if something like this worth to be mentioned as an alternative list of sources in the readme.

Just let me know and I'll send a pull request adding this.

BTW, what RSS reader are you using?

Thanks.

**Comment by jeffbarr** [comment]
This is an awesome list, but I believe it is a bit too general. If you can find a subset of those blogs that cover AWS topics on a regular basis, please go ahead and add them to the existing OPML list. 

> BTW, what RSS reader are you using?

I am using Feedly. A long time ago I wrote a desktop news reader called Headline Viewer, and later built and ran the Syndic8 site to collect lists of feeds. Those efforts ended up getting in to AWS so it was time well spent!

**Comment by inakiabt** [comment]
I think I used Syndic8 in the past too!
After Google Reader shutdown my life wasn't the same :). I tried a lot of
rss readers but I never found the right one. Now my sources are Reddit,
HackerNews and some AWS Blogs RSS + IFTTT -> Email.

I feel like if a tech article worth to be read today it will appear on
these channels.
