### ISSUE TITLE
Is week in review git publishing still maintained?

### ISSUE THREAD

**Issue by ezeeetm** [aws/aws-week-in-review#430]
no commits since 11.21.2016

Are we still using this?

**Comment by matalo33** [comment]
What happened? Why did these suddenly stop?

**Comment by mistwire** [comment]
There hasn't been one since mid November :-(

I hope Jeff is ok.


Regards,

Chris Williams
www.mistwire.com

**Comment by bwhaley** [comment]
The week in review is still being published ([here is the week in review from Feb 20](https://aws.amazon.com/blogs/aws/aws-week-in-review-february-20-2017/)), but is @jeffbarr still accepting community contributions?

**Comment by thapakazi** [comment]
Same things spinning on top of my head. [I found reviews till march ](https://aws.amazon.com/blogs/aws/category/week-in-review/)

**Comment by jeffbarr** [comment]
The Week in Review is no longer being published - there was simply too much good material to process. The efficiency that I gained via the open source model was overrun by the additional contributions that flooded in as a result. 

You can visit [https://aws.amazon.com/new/](https://aws.amazon.com/new/) to track the latest product, service, and feature announcements from AWS.
